# Generated by Django 5.2.8 on 2025-12-25 22:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Organization name", max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique organization code (e.g., 'ACME', 'SINOPEC')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Organization description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo",
                        null=True,
                        upload_to="organizations/logos/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this organization is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=50
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department", max_length=200
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, help_text="Job title", max_length=200),
                ),
                (
                    "language",
                    models.CharField(
                        default="en",
                        help_text="Preferred language (e.g., 'en', 'zh-CN')",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="User timezone", max_length=50
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="User avatar",
                        null=True,
                        upload_to="users/avatars/",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="administration.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTaskForce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_id",
                    models.IntegerField(
                        default=0,
                        help_text="ProjectTenant ID (references tenants.ProjectTenant)",
                    ),
                ),
                ("name", models.CharField(help_text="Task force name", max_length=200)),
                ("code", models.CharField(help_text="Task force code", max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Task force description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this task force is active"
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task force leader",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_task_forces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Task Force",
                "verbose_name_plural": "Project Task Forces",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Role name (e.g., 'Instrumentation Engineer')",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Role code (e.g., 'INST_ENG', 'PROC_ENG')",
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Guest"),
                            (2, "Engineer Level 2"),
                            (3, "Engineer Level 3"),
                            (4, "Project Engineer"),
                            (5, "Administrator"),
                        ],
                        default=1,
                        help_text="Role hierarchy level (1-5)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Role description"),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Permission matrix. Example: {'tag': ['create', 'read', 'update'], 'loop': ['read']}",
                    ),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False, help_text="System roles cannot be deleted"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this role belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="administration.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["-level", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_id",
                    models.IntegerField(
                        default=0,
                        help_text="ProjectTenant ID (references tenants.ProjectTenant)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this membership is active"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role in this project",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_memberships",
                        to="administration.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Membership",
                "verbose_name_plural": "Project Memberships",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="User's role",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="administration.role",
            ),
        ),
        migrations.CreateModel(
            name="TaskForceMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        default="member",
                        help_text="Role in task force (e.g., 'leader', 'member')",
                        max_length=50,
                    ),
                ),
                (
                    "task_force",
                    models.ForeignKey(
                        help_text="Task force",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="administration.projecttaskforce",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_force_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Force Membership",
                "verbose_name_plural": "Task Force Memberships",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ProjectTenant ID (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        help_text="Action performed",
                        max_length=10,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name (e.g., 'Tag', 'Loop')", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the affected object", max_length=100
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the object",
                        max_length=500,
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="Values before the change"
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True, default=dict, help_text="Values after the change"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="Client user agent", max_length=500
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action occurred"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="administration.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-timestamp"],
                        name="administrat_organiz_a0715e_idx",
                    ),
                    models.Index(
                        fields=["project_id", "-timestamp"],
                        name="administrat_project_3ff084_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="administrat_user_id_0f8133_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="administrat_model_n_ad7686_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="projecttaskforce",
            constraint=models.UniqueConstraint(
                fields=("project_id", "code"), name="unique_task_force_code_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_role_code_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "project_id"), name="unique_user_project_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskforcemembership",
            constraint=models.UniqueConstraint(
                fields=("user", "task_force"), name="unique_user_task_force_membership"
            ),
        ),
    ]
