# Generated by Django 5.2.8 on 2025-12-25 22:02

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Client/owner name", max_length=300),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Client code (e.g., 'SINOPEC', 'CNPC')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, help_text="Primary contact person", max_length=200
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Contact email", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Contact phone", max_length=50
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Client address")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the instrument type", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., 'FT', 'TT', 'CV', 'PSV')",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TRANSMITTER", "Transmitter"),
                            ("CONTROL_VALVE", "Control Valve"),
                            ("SWITCH", "Switch"),
                            ("INDICATOR", "Indicator"),
                            ("ANALYZER", "Analyzer"),
                            ("SENSOR", "Sensor"),
                            ("CONTROLLER", "Controller"),
                            ("RECORDER", "Recorder"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Instrument category",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this instrument type"
                    ),
                ),
                (
                    "schema_template",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema defining the required specification fields. Example: {'type': 'object', 'properties': {'range_min': {'type': 'number'}, ...}}",
                    ),
                ),
                (
                    "default_spec_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Default values for spec_data when creating new tags",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this instrument type is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Type",
                "verbose_name_plural": "Instrument Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="NamingConvention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Convention name (e.g., 'ISA-5.1 Standard')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Convention description"),
                ),
                (
                    "hierarchy_format",
                    models.CharField(
                        choices=[
                            ("FULL", "Site-Plant-Area-Unit-Function-Sequence"),
                            ("NO_SITE", "Plant-Area-Unit-Function-Sequence"),
                            ("NO_SITE_PLANT", "Area-Unit-Function-Sequence"),
                            ("UNIT_ONLY", "Unit-Function-Sequence"),
                            ("FLEXIBLE_PREFIX", "XXXX-Unit-Function-Sequence"),
                            ("CUSTOM", "Custom Regex"),
                        ],
                        default="UNIT_ONLY",
                        help_text="Hierarchy format type",
                        max_length=20,
                    ),
                ),
                (
                    "regex_pattern",
                    models.CharField(
                        help_text="Regex pattern for validation. Example: ^[A-Z]{2,3}-\\d{3}[A-Z]?$",
                        max_length=500,
                    ),
                ),
                (
                    "segment_definitions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Segment definitions. Example: [{'name': 'function', 'type': 'letters', 'length': 2}, ...]",
                    ),
                ),
                (
                    "example_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Example valid tags for this convention",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the default convention",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this convention is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Naming Convention",
                "verbose_name_plural": "Naming Conventions",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlantHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the hierarchy node", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code/identifier (e.g., 'P-001', 'A-100', 'U-110')",
                        max_length=50,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("PLANT", "Plant"),
                            ("AREA", "Area"),
                            ("UNIT", "Unit"),
                        ],
                        help_text="Type of hierarchy node",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of this node"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this node is active"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Parent node in the hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core_engineering.planthierarchy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant Hierarchy",
                "verbose_name_plural": "Plant Hierarchies",
            },
        ),
        migrations.CreateModel(
            name="Loop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loop_tag",
                    models.CharField(
                        help_text="Unique loop identifier (e.g., 'FIC-101', 'TIC-201')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("F", "Flow"),
                            ("T", "Temperature"),
                            ("P", "Pressure"),
                            ("L", "Level"),
                            ("A", "Analysis"),
                            ("C", "Control"),
                            ("H", "Hand/Manual"),
                            ("I", "Indicate"),
                            ("S", "Safety"),
                            ("X", "Other"),
                        ],
                        help_text="Primary measured variable/function",
                        max_length=2,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text="Loop suffix/number (e.g., '101', '201A')",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Loop description/service"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this loop is active"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit this loop belongs to",
                        limit_choices_to={"node_type": "UNIT"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loops",
                        to="core_engineering.planthierarchy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loop",
                "verbose_name_plural": "Loops",
                "ordering": ["loop_tag"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Site name", max_length=300)),
                (
                    "code",
                    models.CharField(
                        help_text="Site code (e.g., 'ZH' for Zhenhai, 'SH' for Shanghai)",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Geographic location", max_length=500
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Site address")),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Site timezone (e.g., 'Asia/Shanghai')",
                        max_length=50,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this site belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="core_engineering.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Plant name (e.g., 'Ethylene Plant', 'Aromatics Unit')",
                        max_length=300,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Plant code (e.g., 'ETH', 'ARO', 'P-001')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Plant description"),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        help_text="Plant capacity (e.g., '1000 KTPA')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this plant is active"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site this plant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plants",
                        to="core_engineering.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plant",
                "verbose_name_plural": "Plants",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag_number",
                    models.CharField(
                        help_text="Instrument tag number (e.g., 'FT-101', 'TIC-201')",
                        max_length=50,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        help_text="Service description (what the instrument measures/controls)",
                        max_length=500,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional description or notes"
                    ),
                ),
                (
                    "spec_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Specification data. Must conform to the instrument_type's schema_template.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("DELETED", "Deleted"),
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of the tag",
                        max_length=20,
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Revision number, incremented on each update",
                    ),
                ),
                (
                    "instrument_type",
                    models.ForeignKey(
                        help_text="Type of instrument",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="core_engineering.instrumenttype",
                    ),
                ),
                (
                    "loop",
                    models.ForeignKey(
                        blank=True,
                        help_text="Loop this tag belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="core_engineering.loop",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit this tag belongs to (required)",
                        limit_choices_to={"node_type": "UNIT"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="core_engineering.planthierarchy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["tag_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="planthierarchy",
            constraint=models.UniqueConstraint(
                fields=("parent", "code"), name="unique_code_per_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                fields=("client", "code"), name="unique_site_code_per_client"
            ),
        ),
        migrations.AddConstraint(
            model_name="plant",
            constraint=models.UniqueConstraint(
                fields=("site", "code"), name="unique_plant_code_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("unit", "tag_number"), name="unique_tag_per_unit"
            ),
        ),
    ]
