# Generated by Django 5.2.8 on 2025-12-25 22:01

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Project name", max_length=300)),
                (
                    "project_no",
                    models.CharField(
                        help_text="Project number (e.g., 'PRJ-2024-001')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "organization_id",
                    models.IntegerField(
                        help_text="Organization ID this project belongs to"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        help_text="Project status",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Project end date", null=True
                    ),
                ),
                (
                    "hierarchy_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Hierarchy configuration. Example: {'template': 'standard', 'levels': ['site', 'plant', 'area', 'unit']}",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Tenant",
                "verbose_name_plural": "Project Tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.projecttenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Domain",
                "verbose_name_plural": "Project Domains",
            },
        ),
    ]
